### ISSUE TITLE
PGP key is missing

### ISSUE THREAD

**Issue by sergeevabc** [unredacted/xmpp.is#3]
Dear @lunarthegrey and @nyxnor,

There is a page https://xmpp.is/about/transparency/
that mentions https://keybase.io/cryptoworld/key.asc
I click that link and get 'SELF-SIGNED PUBLIC KEY NOT FOUND'.

Are you signaling that spec ops twisted your arms and the service is no longer safe or is it just a mistake due to absent-mindedness?

**Comment by lunarthegrey** [comment]
Hi @sergeevabc thanks for pointing that out, I can confirm we haven't been spec ops'd :)

Just note that @nyxnor is not a part of the project.

I deleted the cryptoworld keybase account recently as we switched our name a while back; https://unredacted.org/blog/2021/04/crypto-world-is-now-unredacted/

I've updated the text on https://xmpp.is/about/transparency/ to reflect our original PGP key that has been used since 2015.

**Comment by lunarthegrey** [comment]
Edit: decided to update the page with this key https://keybase.io/unredacted_org/pgp_keys.asc?fingerprint=258381c2e19871b35a1460f765af784427430ad2

https://keybase.io/unredacted_org is our new keybase.
